### ISSUE TITLE
Allowed memory size exhausted

### ISSUE THREAD

**Issue by winzou** [schmittjoh/JMSDebuggingBundle#27]
I encounter this error `Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 50696 bytes) in asso\vendor\symfony\src\Symfony\Component\HttpKernel\DataCollector\DataCollector.php on line 29` in 2 cases :
- When I throw an Exception from a factory_method. I've defined a service like that:
  
  ```
  winzou_cache.cache:
      factory_service: winzou_cache.factory
      factory_method:  build
      class: winzou\CacheBundle\Cache\FileCache
      arguments:
          - %winzou_cache.driver.default%
  ```
  
  and if I throw an Exception in the build method of my winzou_cache.factory service, I got this error. Everything works well when I don't throw any exception.
- When I define the same service but with abstract: true and without class:
  
  ```
  winzou_cache.cache:
      factory_service: winzou_cache.factory
      factory_method:  build
      abstract: true
      arguments:
          - %winzou_cache.driver.default%
  ```
  
  I don't throw any exception in that case. Actually, if I put an exit('foo') in my factory file (at the very beginning), it's not even executed.

After investigation, I've found that in both case a FlattenException is thrown. In the first case it's mine, in the second case it's a "You have requested a non-existent service "winzou_cache.cache"." one (maybe I misuse the abstract way of defining a service, that's another problem).

I don't have this error when I don't override AppKernel/getContainerBaseClass() according to the doc of this bundle.
